server:
  port: 8080

token:
  header: Authorization
  secret: 6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-
  timeout: 10800

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/base?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  servlet:
    # 设置文件上传大小控制
    multipart:
      max-file-size: 128MB
      max-request-size: 256MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  title: Api Document
  enable: true

oss:
  # 七牛云配置
  qiniu:
    access-key: fMSA1fhr2LNv_93_aiZqI8ONM9JrF_iGnMlasT26
    secret-key: UOhvNlIAfoBf9Ar0bF3vu46YwXefN2OiWJdlguYG
    bucket-name: my-blog-bucket
    prefix-link: http://img.cdn.linzhaoming.com/