server:
  port: 8080

jwt:
  secret: 6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-
  timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://47.103.195.154:3306/base?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qwe#123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl